package com.myth.social;

/**
 * Created by mitesh on 26/01/16.
 */
public enum EventType {
    GET_LIKES,
    LIKE_OBJECT,
    ADD_COMMENT,
    UPDATE_COMMENT,
    DELETE_COMMENT,
    READ_COMMENTS,
    UNLIKE_OBJECT,
    CREATE_CHANNEL,
    DELETE_CHANNEL,
    READ_CHANNELS,
    SUBSCRIBE_CHANNEL,
    UNSUBSCRIBE_CHANNEL,
    READ_CHANNEL_DETAIL,
    ADD_CHANNEL_PROPERTY,
    READ_CHANNEL_PROPERTY,
    SHARE_OBJECT_CHANNEL,
    READ_SHARED_OBJECTS_CHANNEL,
    DELETE_SHARED_OBJECT_CHANNEL;
}
